language: php

# faster builds on new travis setup not using sudo
sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

cache:
    directories:
        - $HOME/.composer/cache/
        - vendor

install:
    # Install dependencies
    - travis_retry composer self-update && composer --version
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry composer install --prefer-dist -n

script:
    # Run tests
    - bin/phpunit -c phpunit.xml $PHPUNIT_FLAGS

after_failure:
    # Display error logs
    - cat /var/log/php_errors.log
